# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'brookmint'

[general]
title = "House Of Prompts"
logo = ""
iconLogo = "tabler:coffee"

[general.seo]
name = "House Of Prompts Directory"
description = "Find the best AI prompts."
url = "https://nuxtstarters.com"

[directoryData.source]
name = "markdown"    # default, mock, sheets, json, notion
links = "normal"

[directoryData.tagPages]
title = "{0} Prompts"

[directoryData.search]
placeholder = "Search among {0} lprompts of this directory"

[[directoryData.tags]]
key = "copilot"
name = "Github Copilot"
color = "blue"
emoji = "👨‍✈️"
description = "Custom GitHub Copilot prompts."

[[directoryData.tags]]
key = "chat-mode"
name = "Chat Mode"
color = "blue"
emoji = "💬"
description = "Custom GitHub Copilot prompts."

[[directoryData.tags]]
key = "breathing"
name = "Breathing"
color = "blue"
emoji = "👃"
description = "Breathing techniques are a popular feature in meditation apps."

[header.banner]
show = true
text = "Follow maxfaber_Om on twitter."
link = "https://x.com/intent/follow?screen_name=maxfaber_Om"
brandText = "AI Agent Libraries"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Blog"
href = "/blog"

[[header.navbar.links]]
name = "Analytics"
href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
target = "_blank"

[header.actionButton]
text = "Submit a prompt"
href = "https://tally.so"

[footer]
description = "Best directory for AI prompts."

[footer.socials.x]
link = "https://x.com/maxfaber_Om"

[footer.socials.youtube]
link = "https://www.youtube.com/@mkznvv"
