#!/usr/bin/env npx tsx
/**
 * Sync Generate Script
 *
 * Generates Astro directory entries from synced files in sources/ folder.
 * Each file gets a corresponding entry in src/data/directory/ with proper
 * frontmatter for the Astro website to consume.
 *
 * Usage:
 *   pnpm sync:generate          - Generate all directory entries
 *   pnpm sync:generate --dry    - Preview what would be generated
 *   pnpm sync:generate --clean  - Remove generated entries not in sources/
 */

import * as fs from 'fs';
import * as path from 'path';

// ============================================================================
// Types
// ============================================================================

interface DirectoryEntry {
  title: string;
  description: string;
  tags: string[];
  link: string;
  image: string;
  sourcePath: string;
  sourceCategory: string;
  content: string;
}

interface GenerateResult {
  source: string;
  target: string;
  status: 'created' | 'updated' | 'skipped' | 'deleted';
  message?: string;
}

// ============================================================================
// Configuration
// ============================================================================

const REPO_ROOT = path.resolve(import.meta.dirname, '..');
const SOURCES_DIR = path.join(REPO_ROOT, 'sources');
const DIRECTORY_DIR = path.join(REPO_ROOT, 'src/data/directory');

const CATEGORIES = ['agents', 'hooks', 'memory', 'skills', 'scripts', 'knowledge', 'papers'] as const;
type Category = typeof CATEGORIES[number];

// Frontmatter marker to identify generated files
const GENERATED_MARKER = '<!-- GENERATED_BY_SYNC_GENERATE -->';

// ============================================================================
// File Operations
// ============================================================================

function getSourceFiles(): { path: string; category: Category }[] {
  const files: { path: string; category: Category }[] = [];

  for (const category of CATEGORIES) {
    const categoryDir = path.join(SOURCES_DIR, category);

    if (!fs.existsSync(categoryDir)) continue;

    const entries = fs.readdirSync(categoryDir, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isFile() && !entry.name.startsWith('.') && entry.name !== '.gitkeep') {
        files.push({
          path: path.join(categoryDir, entry.name),
          category,
        });
      }
    }
  }

  return files;
}

function createDirectoryEntry(
  sourcePath: string,
  category: Category
): DirectoryEntry {
  const filename = path.basename(sourcePath);
  const content = fs.readFileSync(sourcePath, 'utf-8');

  // Extract title from filename (remove extension)
  const title = filename.replace(/\.[^.]+$/, '');

  // Create description placeholder
  const description = `TODO: Add description for ${title}`;

  return {
    title,
    description,
    tags: [category],
    link: '',
    image: '',
    sourcePath,
    sourceCategory: category,
    content,
  };
}

function generateMarkdown(entry: DirectoryEntry): string {
  const frontmatter = `---
title: ${entry.title}
description: ${entry.description}
tags:
${entry.tags.map(tag => `  - ${tag}`).join('\n')}
link: ${entry.link}
image: ${entry.image}

---
${GENERATED_MARKER}
## Description

${entry.description}

## Source

Category: **${entry.sourceCategory}**

## Content

\`\`\`markdown
${entry.content}
\`\`\`
`;

  return frontmatter;
}

function generateEntry(
  sourcePath: string,
  category: Category,
  dryRun: boolean
): GenerateResult {
  const filename = path.basename(sourcePath);
  const targetPath = path.join(DIRECTORY_DIR, filename);

  const entry = createDirectoryEntry(sourcePath, category);
  const markdown = generateMarkdown(entry);

  if (dryRun) {
    return {
      source: sourcePath,
      target: targetPath,
      status: 'created',
      message: 'Would generate (dry run)',
    };
  }

  // Check if file already exists and was generated by us
  if (fs.existsSync(targetPath)) {
    const existingContent = fs.readFileSync(targetPath, 'utf-8');
    if (!existingContent.includes(GENERATED_MARKER)) {
      return {
        source: sourcePath,
        target: targetPath,
        status: 'skipped',
        message: 'File exists and was not generated by sync (manual edit)',
      };
    }
  }

  try {
    fs.writeFileSync(targetPath, markdown);
    return {
      source: sourcePath,
      target: targetPath,
      status: fs.existsSync(targetPath) ? 'updated' : 'created',
    };
  } catch (error) {
    return {
      source: sourcePath,
      target: targetPath,
      status: 'skipped',
      message: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

function cleanOrphanedFiles(dryRun: boolean): GenerateResult[] {
  const results: GenerateResult[] = [];

  if (!fs.existsSync(DIRECTORY_DIR)) return results;

  // Get all source filenames
  const sourceFiles = getSourceFiles();
  const sourceFilenames = new Set(sourceFiles.map(f => path.basename(f.path)));

  // Check directory files
  const directoryFiles = fs.readdirSync(DIRECTORY_DIR, { withFileTypes: true });

  for (const entry of directoryFiles) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;

    const filePath = path.join(DIRECTORY_DIR, entry.name);
    const content = fs.readFileSync(filePath, 'utf-8');

    // Only clean files we generated
    if (!content.includes(GENERATED_MARKER)) continue;

    // Check if source still exists
    if (!sourceFilenames.has(entry.name)) {
      if (dryRun) {
        results.push({
          source: filePath,
          target: filePath,
          status: 'deleted',
          message: 'Would delete (dry run)',
        });
      } else {
        try {
          fs.unlinkSync(filePath);
          results.push({
            source: filePath,
            target: filePath,
            status: 'deleted',
          });
        } catch (error) {
          results.push({
            source: filePath,
            target: filePath,
            status: 'skipped',
            message: error instanceof Error ? error.message : 'Unknown error',
          });
        }
      }
    }
  }

  return results;
}

// ============================================================================
// Main Functions
// ============================================================================

function generate(dryRun: boolean = false): GenerateResult[] {
  const results: GenerateResult[] = [];

  // Ensure directory exists
  if (!dryRun && !fs.existsSync(DIRECTORY_DIR)) {
    fs.mkdirSync(DIRECTORY_DIR, { recursive: true });
  }

  // Get all source files
  const sourceFiles = getSourceFiles();

  // Generate entries for each source file
  for (const { path: sourcePath, category } of sourceFiles) {
    const result = generateEntry(sourcePath, category, dryRun);
    results.push(result);
  }

  return results;
}

// ============================================================================
// Output Display
// ============================================================================

function printResults(results: GenerateResult[], dryRun: boolean): void {
  const title = dryRun ? '🔍 Dry Run - Generate Preview' : '✅ Generate Complete';
  console.log(`\n${title}\n`);
  console.log('─'.repeat(80));

  let createdCount = 0;
  let updatedCount = 0;
  let skippedCount = 0;
  let deletedCount = 0;

  for (const result of results) {
    const icon = result.status === 'created' ? '📄' :
                 result.status === 'updated' ? '✏️' :
                 result.status === 'deleted' ? '🗑️' : '⏭️';

    if (result.status === 'created') createdCount++;
    else if (result.status === 'updated') updatedCount++;
    else if (result.status === 'deleted') deletedCount++;
    else skippedCount++;

    const relativeTarget = path.relative(REPO_ROOT, result.target);
    const relativeSource = path.relative(REPO_ROOT, result.source);

    console.log(`\n${icon} [${result.status}] ${relativeTarget}`);
    if (result.status !== 'deleted') {
      console.log(`   ← ${relativeSource}`);
    }
    if (result.message) {
      console.log(`   ${result.message}`);
    }
  }

  console.log('\n' + '─'.repeat(80));
  console.log(`\n📊 Summary: ${createdCount} created, ${updatedCount} updated, ${deletedCount} deleted, ${skippedCount} skipped\n`);

  if (!dryRun && (createdCount > 0 || updatedCount > 0 || deletedCount > 0)) {
    console.log('💡 Next steps:');
    console.log('   1. Edit descriptions in generated files');
    console.log('   2. Run `pnpm dev` to preview on website');
    console.log('   3. Commit with: git add src/data/directory/ && git commit\n');
  }
}

function printUsage(): void {
  console.log(`
Usage: sync-generate.ts [options]

Options:
  --dry, -d     Preview what would be generated without writing
  --clean, -c   Also remove generated files whose source no longer exists
  --help, -h    Show this help message

Examples:
  pnpm sync:generate           Generate directory entries
  pnpm sync:generate --dry     Preview changes
  pnpm sync:generate --clean   Generate and clean orphaned files
`);
}

// ============================================================================
// CLI
// ============================================================================

const args = process.argv.slice(2);

if (args.includes('--help') || args.includes('-h')) {
  printUsage();
  process.exit(0);
}

const dryRun = args.includes('--dry') || args.includes('-d');
const shouldClean = args.includes('--clean') || args.includes('-c');

// Generate entries
const results = generate(dryRun);

// Clean orphaned files if requested
if (shouldClean) {
  const cleanResults = cleanOrphanedFiles(dryRun);
  results.push(...cleanResults);
}

printResults(results, dryRun);
